baseURL = 'https://www.fewlines.com.ar/'
languageCode = 'es-ar'
title = 'FewLines'
theme = 'fewlines-theme'

# Configuraci√≥n para GitHub Pages
publishDir = "../docs"

[params]
  description = "Desarrollamos soluciones simples para problemas complejos"
  whatsapp = "5491165177711"
  favicon = "/FL_gris.ico"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML"]
